name: Java CI

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Compile Java files
        run: |
          mkdir -p out
          javac -cp "lib/*" -d out $(find src -name "*.java")

      - name: Run tests
        run: |
          java -cp "out:lib/*" org.junit.platform.console.ConsoleLauncher --scan-class-path

      - name: Create fat JAR file
        run: |
          mkdir -p dist/tmp_classes
          mkdir -p dist/tmp_libs

          # Распаковываем все библиотеки
          for jarfile in lib/*.jar; do
            unzip -o -q "$jarfile" -d dist/tmp_libs
          done

          # Копируем свои .class файлы
          cp -r out/* dist/tmp_classes/

          # Создаём manifest с указанием Main-класса
          echo "Main-Class: uz.cherevichenko_sergey.cafe_order_system.MainClass" > manifest.txt

          # Собираем fat-jar
          jar cfm dist/CafeOrderSystem-fat.jar manifest.txt -C dist/tmp_libs . -C dist/tmp_classes .

      - name: Upload fat JAR artifact
        uses: actions/upload-artifact@v4
        with:
          name: CafeOrderSystem-fat-jar
          path: dist/CafeOrderSystem-fat.jar
